"""Create user and lifestyle tables

Revision ID: 08b1ae2bad98
Revises: 69cef70b013e
Create Date: 2025-05-05 13:41:41.402507

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '08b1ae2bad98'
down_revision = '69cef70b013e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lifestyle_data', schema=None) as batch_op:
        batch_op.add_column(sa.Column('timestamp', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lifestyle_data', schema=None) as batch_op:
        batch_op.drop_column('timestamp')

    # ### end Alembic commands ###
