"""add LifestyleData

Revision ID: 3648aa9035b4
Revises: bb7981a826c1
Create Date: 2025-05-05 12:56:48.085961

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '3648aa9035b4'
down_revision = 'bb7981a826c1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lifestyle_data', schema=None) as batch_op:
        batch_op.add_column(sa.Column('age', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('height', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('weight', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('activity_level', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('water_intake', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('diet_preference', sa.String(length=50), nullable=False))
        batch_op.drop_column('stress_level')
        batch_op.drop_column('timestamp')
        batch_op.drop_column('diet_quality')
        batch_op.drop_column('exercise_minutes')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lifestyle_data', schema=None) as batch_op:
        batch_op.add_column(sa.Column('exercise_minutes', mysql.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('diet_quality', mysql.VARCHAR(length=100), nullable=False))
        batch_op.add_column(sa.Column('timestamp', mysql.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('stress_level', mysql.VARCHAR(length=100), nullable=False))
        batch_op.drop_column('diet_preference')
        batch_op.drop_column('water_intake')
        batch_op.drop_column('activity_level')
        batch_op.drop_column('weight')
        batch_op.drop_column('height')
        batch_op.drop_column('age')

    # ### end Alembic commands ###
