"""Update LifestyleData fields

Revision ID: 69cef70b013e
Revises: 3648aa9035b4
Create Date: 2025-05-05 13:03:30.125973

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '69cef70b013e'
down_revision = '3648aa9035b4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lifestyle_data', schema=None) as batch_op:
        batch_op.add_column(sa.Column('diet_quality', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('exercise_minutes', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('stress_level', sa.String(length=50), nullable=False))
        batch_op.drop_column('diet_preference')
        batch_op.drop_column('activity_level')
        batch_op.drop_column('height')
        batch_op.drop_column('age')
        batch_op.drop_column('weight')
        batch_op.drop_column('water_intake')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lifestyle_data', schema=None) as batch_op:
        batch_op.add_column(sa.Column('water_intake', mysql.FLOAT(), nullable=False))
        batch_op.add_column(sa.Column('weight', mysql.FLOAT(), nullable=False))
        batch_op.add_column(sa.Column('age', mysql.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('height', mysql.FLOAT(), nullable=False))
        batch_op.add_column(sa.Column('activity_level', mysql.VARCHAR(length=50), nullable=False))
        batch_op.add_column(sa.Column('diet_preference', mysql.VARCHAR(length=50), nullable=False))
        batch_op.drop_column('stress_level')
        batch_op.drop_column('exercise_minutes')
        batch_op.drop_column('diet_quality')

    # ### end Alembic commands ###
