"""Add LifestyleData model

Revision ID: bb7981a826c1
Revises: 3b434107a657
Create Date: 2025-05-05 12:40:30.129235

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bb7981a826c1'
down_revision = '3b434107a657'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lifestyle_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sleep_hours', sa.Float(), nullable=False),
    sa.Column('diet_quality', sa.String(length=100), nullable=False),
    sa.Column('exercise_minutes', sa.Integer(), nullable=False),
    sa.Column('stress_level', sa.String(length=100), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('lifestyle_data')
    # ### end Alembic commands ###
